### ISSUE TITLE
32-bit architecture when?

### ISSUE THREAD

**Issue by TheEZIC** [l3lackShark/gosumemory#11]

**Comment by l3lackShark** [comment]
Due to the way we scan for signatures, program can crash on 32bit. What is your use case? Win32 or Linux under WINE?

**Comment by TheEZIC** [comment]
Win10 32-bit

**Comment by l3lackShark** [comment]
Experimental 32-Bit support is added in the latest release. Please report stability here.

**Comment by l3lackShark** [comment]
Should be fixed since 1.1.0
