### ISSUE TITLE
 ERROR: no memory matched the pattern: 0A D7 23 3C 00 00 ?? 01

### ISSUE THREAD

**Issue by SSagun-c** [l3lackShark/gosumemory#113]
This suddenly showed up, yesterday it was working all fine.

![img_003](https://user-images.githubusercontent.com/81767182/146686484-54082b0d-f8b0-436d-a09a-9824341d69d8.jpg)

**Comment by WoahItzSwagger** [comment]
I've been getting this "error" as well, I don't know what's going on maybe because you have osu open or something?

**Comment by BubblegumZen** [comment]
Same issue here, on linux

**Comment by l3lackShark** [comment]
> Simiilar issue here, on linux

Use dotnet 4.5 wineprefix (osu-wine f.e.)

**Comment by SSagun-c** [comment]
I am kind of late but gosumemory (as for me) does not work (well) wih osu! cutting edge, so better consider using stable!
