### ISSUE TITLE
Ingame overlay pp not accurate

### ISSUE THREAD

**Issue by 5oulReaper14** [l3lackShark/gosumemory#115]
![image](https://user-images.githubusercontent.com/53729705/147463828-d2c149e6-5983-48c7-98dd-fced72d00c9b.png)
as you can see from the top left it says 140 while in the performance i got 122

**Comment by YAUIO** [comment]
It hasn't got updated yet. Blackshark is rewriting it, but slowly because of the lack of free time

**Comment by l3lackShark** [comment]
1.3.5
