### ISSUE TITLE
pp counter stays at 0pp forever

### ISSUE THREAD

**Issue by Tozitt** [l3lackShark/gosumemory#117]

**Comment by Tozitt** [comment]
![image](https://user-images.githubusercontent.com/97464361/148803413-c156c7a7-538b-43f8-9cf9-621cf043d37b.png)

**Comment by robloxxa** [comment]
Can you provide a console screenshot while in gameplay? 
If you have an Fopen error that means your path contains non-English characters 
or 
you run osu with admin privileges

**Comment by Tozitt** [comment]
[image: image.png]
this message keeps appearing

Em seg., 10 de jan. de 2022 às 10:05, robloxxa ***@***.***>
escreveu:

**Comment by robloxxa** [comment]
Where is your osu! located? This error in many cases appears when you have non-english characters in folder path.
Move osu folder to something like `C:\osu!\` and you should be fine

**Comment by Tozitt** [comment]
it worked bro tysm!!

**Comment by Tozitt** [comment]
i moved it to another place and it worked.
