### ISSUE TITLE
"Expected mp3, got something else. Aborting mp3 time calculation. GOT: " ""

### ISSUE THREAD

**Issue by Pieisthetruth** [l3lackShark/gosumemory#129]
I've received this error in the past and was fixed by opening the program after osu was open. But this time no fix. Another time I had an issue(that might have been separate)e I just updated it as well. I tried disabling my firewall/antivirus and reinstalling gosu and that didn't work either. Now I'm out of luck. I hope I can get it fixed soon. Thanks :)

**Comment by l3lackShark** [comment]
Duplicate

https://github.com/l3lackShark/gosumemory/issues/128#issuecomment-1090483696
