### ISSUE TITLE
Failure mid getting offsets, no memory matched the pattern

### ISSUE THREAD

**Issue by LMFuture-Me** [l3lackShark/gosumemory#140]
2022/06/17 20:12:29 Failure mid getting offsets, retrying! ERROR: no memory matched the pattern: 83 E0 20 85 C0 7E 2F
on wine 7.10
![image](https://user-images.githubusercontent.com/36117602/174296000-804754ba-7d2d-46ca-b202-b61c15ae188a.png)

**Comment by Sclafus** [comment]
Since you are on linux, are you running gosumemory as root? gosumemory needs to read stuff in `/proc` (literally the first line of the readme)

**Comment by LMFuture-Me** [comment]
> Since you are on linux, are you running gosumemory as root? gosumemory needs to read stuff in `/proc` (literally the first line of the readme)

Yes. I can neither run it directly nor with wine

**Comment by parhelia3** [comment]
@LMFuture-Me To fix this issue you need to install `dotnet45` to your Wine prefix.

At least in my case I'd do something like this: `WINEARCH=win32 WINEPREFIX=~/.wineosu winetricks dotnet45`; however you're free to install `dotnet45` with whatever is the most convenient option for you.

After installing, close the game if you had it open, run the game again and gosumemory will start working as normal.

**Comment by LMFuture-Me** [comment]
Fixed. Thx
