### ISSUE TITLE
Weird bug, can't see graph for one specific song

### ISSUE THREAD

**Issue by excitedsoup** [l3lackShark/gosumemory#148]
![ec8948bcdcdf779766b4455c01328637](https://user-images.githubusercontent.com/65786240/187112882-a291ab55-47bd-4cf0-87c0-b7158005aaf1.png)

This is what I'm seeing, most songs will show the graph on oldclassic or classic, but not this one specifically

**Comment by l3lackShark** [comment]
ogg music format is not supported
