### ISSUE TITLE
pp counter doesn't update

### ISSUE THREAD

**Issue by PearooXD** [l3lackShark/gosumemory#182]
The pp counter doesn't work when I add it as an OBS source or when I have the in game overlay turned on. Idk if it's just me, I use Simplistic http://localhost:24050/Simplistic/ but I tried reComfortaa too and that doesn't work too. Simplistic shows PP if SS in song select though

**Comment by KotRikD** [comment]
Please download latest artifact from https://github.com/l3lackShark/gosumemory/actions/runs/4573585206 , should help btw

**Comment by Kaillr** [comment]
Thanks. I was having the same issue, this worked

**Comment by Parleydayo** [comment]
> Please download latest artifact from https://github.com/l3lackShark/gosumemory/actions/runs/4573585206 , should help btw

how do i do that?

**Comment by walletstealer96** [comment]
How do I download 

> Please download latest artifact from https://github.com/l3lackShark/gosumemory/actions/runs/4573585206 , should help btw

How do I download the artifact?

**Comment by ToastedDev** [comment]
> How do I download the artifact?

scroll down, you should see a section that says "artifacts".

**Comment by fyaakkk** [comment]
How i can download it?

**Comment by cyperdark** [comment]
You too late they are deleted, now download it from there https://github.com/KotRikD/gosumemory/actions/runs/7239749608
