### ISSUE TITLE
pp counter doesnt work while playing

### ISSUE THREAD

**Issue by manuleeel** [l3lackShark/gosumemory#183]
Ive seen others have the same problem. When I select a song the pp counter is working before but when I play it doenst react on my gameplay.

**Comment by cubigiabinh** [comment]
download the lastest artifacts from here with new offsets https://github.com/l3lackShark/gosumemory/actions/runs/4573585206

**Comment by cyperdark** [comment]
try this one @manuleeel https://github.com/l3lackShark/gosumemory/actions/runs/4573585206 and tell if its fixed your issue
