### ISSUE TITLE
Memory Offsets Change Again?

### ISSUE THREAD

**Issue by R0B11** [l3lackShark/gosumemory#184]
Did memory offsets change again ? Using latest release (Apr 6) and I have missing information like gameplay.name on cutting edge. Missing mod strings while in tournament mode as well

**Comment by R0B11** [comment]
![image](https://user-images.githubusercontent.com/114362409/230198150-c3bd726d-9add-4dca-8d20-3ea516cf5850.png)

**Comment by cyperdark** [comment]
this one fixed my issue https://github.com/l3lackShark/gosumemory/actions/runs/4573585206

can i ask you to try it as well?
