### ISSUE TITLE
pp not updating in game

### ISSUE THREAD

**Issue by TopKekTim** [l3lackShark/gosumemory#186]
I know this is an issue with a few posts but all I can see is stuff about artifacts and offsets. How do I fix this issue idk what to do. I re-downloaded the most recent release yesterday still not working.

**Comment by DanielPower** [comment]
A fix has recently been merged, but a new release has not been created yet.

In the mean time, you can use the build that was included with the fix. See the post here: https://github.com/l3lackShark/gosumemory/pull/177#issuecomment-1474091004

**Comment by TopKekTim** [comment]
awesome thank you for your help
