### ISSUE TITLE
Gosu not working in game

### ISSUE THREAD

**Issue by ItsMiku** [l3lackShark/gosumemory#188]
The counter in game don t work (i have the lastest vesion) the in game counter work only in song selection but in gameplay all the number stary to 0

**Comment by Corvus-alt** [comment]
I have exactly the same issue

**Comment by wTylur** [comment]
same is happening to me. the pp counter shows the amount of pp the map is worth but all values stay zero when I proceed to play. (i have the latest version). this has only started to happen in the last week or 2. @l3lackShark help us (,:

**Comment by DestrosXD** [comment]
> 

it still doesnt work

**Comment by cyperdark** [comment]
@DestrosXD is it not working in cutting edge or stable?
