### ISSUE TITLE
gosumemory when playing beatmap it shows 0pp 

### ISSUE THREAD

**Issue by GamebP** [l3lackShark/gosumemory#189]
you know what i mean,,,

**Comment by DihyahAdib** [comment]
same here someone said to download the latest artifacts but that doesn't work ether

**Comment by Corvus-alt** [comment]
3rd time i comment that i have the same issue

**Comment by Sixtails1** [comment]
I had the same issue, and then I downloaded the latest artifact as suggested in this comment: https://github.com/l3lackShark/gosumemory/issues/182#issuecomment-1492576759. 
This resolved the issue for me, so I would assume that the latest release may differ from the one linked here: https://github.com/l3lackShark/gosumemory/actions/runs/4573585206.

**Comment by DarkFlameMaslter** [comment]
I things there are something wrong with time estimation function. Mine showing error for expected .mp3 in beatmaps sound and got file audio.ogg. Then it abort mp3 time caculation. Also I don't know if there is typo error but I see a " that is left for no reason in error return message too

**Comment by adr1xn666** [comment]
same problem and i have this error for like 2 weeks now (still waiting for a fix)
![image](https://user-images.githubusercontent.com/87035044/233035971-14669f0a-685c-4c7e-8719-7a52a913c8a8.png)

**Comment by GamebP** [comment]
> I had the same issue, and then I downloaded the latest artifact as suggested in this comment: [#182 (comment)](https://github.com/l3lackShark/gosumemory/issues/182#issuecomment-1492576759). This resolved the issue for me, so I would assume that the latest release may differ from the one linked here: https://github.com/l3lackShark/gosumemory/actions/runs/4573585206. For context, I downloaded "gosumemory_windows_amd64."

Works like 4 or 5days ago when this was posted.
