### ISSUE TITLE
mania stats not updating

### ISSUE THREAD

**Issue by lawyercat-osu** [l3lackShark/gosumemory#190]
whenever i play song, none of the stats update, 
![screenshot201](https://user-images.githubusercontent.com/115840710/234724027-b1211471-8224-4277-aae5-51f26472a934.jpg)

**Comment by ToastedDev** [comment]
osu! has recently updated their offsets. download a new version here: https://github.com/l3lackShark/gosumemory/actions/runs/4573585206

**Comment by cyperdark** [comment]
@lawyercat-osu is it fixed your problem?
