### ISSUE TITLE
sv2 score issue

### ISSUE THREAD

**Issue by Siemator** [l3lackShark/gosumemory#193]
gosumemory won't show proper score, when map is played with sv2, it doesn't matter if it is sv2 only or with others mods. It also doesn't matter which map i played. Without sv2 gosu show proper score.

i using version from [Merge pull request #177](https://github.com/l3lackShark/gosumemory/actions/runs/4573585206)

NFDT + SV2:
![obraz](https://github.com/l3lackShark/gosumemory/assets/13433324/c84f0f35-fb53-4a5c-92eb-64fd0004a2f5)
![obraz](https://github.com/l3lackShark/gosumemory/assets/13433324/5c5e59e2-0213-4d9e-8072-37052289f9e7)

SV2 only:
![obraz](https://github.com/l3lackShark/gosumemory/assets/13433324/af91c252-f76a-41b2-81b2-032e810c377b)
![obraz](https://github.com/l3lackShark/gosumemory/assets/13433324/531e40be-48cc-4d6f-95c6-a4425351830c)

NFDT:

![obraz](https://github.com/l3lackShark/gosumemory/assets/13433324/4b53ef6a-5bfa-4fee-82bc-4ad3220d7937)
![obraz](https://github.com/l3lackShark/gosumemory/assets/13433324/cde1d3d9-be0c-4a54-ba68-caa405835473)

**Comment by cyperdark** [comment]
Try this build and let me know if it is still the case or not
https://github.com/l3lackShark/gosumemory/actions/runs/5162677007

**Comment by Siemator** [comment]
works fine now ❤

![obraz](https://github.com/l3lackShark/gosumemory/assets/13433324/c8970cd2-9445-441c-8c84-c1b9dd4ea479)
![obraz](https://github.com/l3lackShark/gosumemory/assets/13433324/c84aaae3-d474-4af3-bf24-a029671386ca)

![obraz](https://github.com/l3lackShark/gosumemory/assets/13433324/969eebab-4bde-4d14-a137-ce58e80fa4f2)
![obraz](https://github.com/l3lackShark/gosumemory/assets/13433324/426dbf9f-2af3-40d6-a95b-80bc41c35c30)
