### ISSUE TITLE
The pp counter is showing up but not working

### ISSUE THREAD

**Issue by Flintytunic55** [l3lackShark/gosumemory#194]
"Expected mp3, got something else. Aborting mp3 time calculation. GOT: " ""
"Expected mp3, got something else. Aborting mp3 time calculation. GOT: " "C:\\Users\\flinty\\AppData\\Local\\osu!\\Songs\\circles.ogg"
fopen: No such file or directory

So if you can please help with this i dont know how to fix it and theres no videos on it. It is showing up in game but not working when i play.

**Comment by Jxcky120** [comment]
You need a static directory which contains all the overlay content. 

Also fix for the pp counter fyi. Download the updated version: https://github.com/l3lackShark/gosumemory/actions/runs/4573585206 . Scroll down to the artifact and then click on the desired download.

**Comment by cyperdark** [comment]
@Flintytunic55 any news?
