### ISSUE TITLE
0 stats on stream/record

### ISSUE THREAD

**Issue by warfey48** [l3lackShark/gosumemory#199]
I have latest version, 0 issues in a gosumemory console, showing total pp for ss and nothing while playing. How i can fix this?
![изображение_2023-05-25_002508690](https://github.com/l3lackShark/gosumemory/assets/132196395/1a639e1c-b24c-4a95-9b72-0920c1f05129)
![изображение_2023-05-25_002600129](https://github.com/l3lackShark/gosumemory/assets/132196395/b001705e-66ab-472b-84a8-516bcb95cdaf)

**Comment by cyperdark** [comment]
can you try version from there?: https://github.com/l3lackShark/gosumemory/actions/runs/4573585206
