### ISSUE TITLE
pp counter broken

### ISSUE THREAD

**Issue by DropNight** [l3lackShark/gosumemory#201]
it works when im in the map select area, but when i start a map, it just says ss and the 100s, 50s, and misses are stuck at 0

also i tried downloading the latest version from https://github.com/l3lackShark/gosumemory/actions/runs/4573585206 but it still didnt work, btw i use simplistic

**Comment by DropNight** [comment]
oh, also it says:

"Expected mp3, got something else. Aborting mp3 to time calculation. Got: " ""
[GAMEOVERLAY] Initialized successfully, see https://github.com/l3lackShark/gosumemory/wiki/GameOverlay for tutorial
"Expected me3, got something else. Aborting mp3 time calculation. GOT:  " "C:\\Users\\-----\\AppData\\Local\\osu!\\Songs\\circles.ogg"
fopen: No such file or directory

in the cmd thing, im not sure if thats related tho

**Comment by cyperdark** [comment]
I just downloaded this build and i worked fine for me (windows)
https://github.com/l3lackShark/gosumemory/actions/runs/4573585206
