### ISSUE TITLE
JSON mod name inconsistency on NoMod

### ISSUE THREAD

**Issue by VictimCrasher** [l3lackShark/gosumemory#21]
JSON snippet on gameplay/replay

```json
...
"mods": {
  "num": 0,
  "str": ""
}
...
```

JSON snippet on song selection/score results

```json
...
"mods": {
  "num": 0,
  "str": "NM"
}
...
```

Should've been an easy fix, I reckon. But I can't code much.

**Comment by Dartandr** [comment]
@VictimCrasher, Most likely this will not be merged other way it cause a lot of problems on already made frontend in custom counters

**Comment by l3lackShark** [comment]
This one's tough. It's a very easy fix, but our hands are tighten because that will break compatibility with all custom counters made so far. Not sure on whether I should do this or not.

**Comment by VictimCrasher** [comment]
Thank you for the response, if it's going to break compatibility then I guess I can let it slide for now.

**Comment by l3lackShark** [comment]
Actually when I took a closer look it I decided to fix it. Will be fixed next release. eafa9bd72f6fccd3f7cf9602ce2852639153589e Thanks for the report.
