### ISSUE TITLE
Problems with changing beatmaps.

### ISSUE THREAD

**Issue by TheEZIC** [l3lackShark/gosumemory#23]
When I change beatmap in song select once response beatmap metadata return nothing (any gamemode).
![image](https://user-images.githubusercontent.com/35061249/91635898-f4707180-ea04-11ea-9097-bad1dbdc1fe1.png)
![image](https://user-images.githubusercontent.com/35061249/91635908-ff2b0680-ea04-11ea-82b5-02a1b3e28d16.png)
On songs endpoint I have only ±6500/100k+ maps
![image](https://user-images.githubusercontent.com/35061249/91635924-2255b600-ea05-11ea-83e6-59809adc9b12.png)

**Comment by l3lackShark** [comment]
Is your songs folder somewhere else? When you start up the program it tells you that path. Is it correct?

**Comment by TheEZIC** [comment]
Yes, it's correct (default folder)

**Comment by l3lackShark** [comment]
Try manually specifying the songs folder path and see if it helps (see -help flag)

**Comment by TheEZIC** [comment]
i don`t understand where help flag is

**Comment by l3lackShark** [comment]
open powershell, launch the program like this:  (specify your path here)
![image](https://user-images.githubusercontent.com/20248967/91640134-c6a32100-ea34-11ea-937e-f5b7ad7dc9c0.png)

**Comment by TheEZIC** [comment]
![image](https://user-images.githubusercontent.com/35061249/91640234-a3707580-ea24-11ea-9ee6-11765c312e0d.png)
![image](https://user-images.githubusercontent.com/35061249/91640242-bedb8080-ea24-11ea-9893-4b047f8247b9.png)
not help

**Comment by l3lackShark** [comment]
Open that folder in Windows explorer and check what number you are seeing in the bottom left corner:
![image](https://user-images.githubusercontent.com/20248967/91640276-cbb4a000-ea35-11ea-9cac-40cc34145f30.png)

**Comment by TheEZIC** [comment]
![image](https://user-images.githubusercontent.com/35061249/91640314-4e812f00-ea25-11ea-943f-a374c16e8a2e.png)
Ok, that is right. But I anyway don't know why programm can't parse metadata (no such file or directory).

**Comment by l3lackShark** [comment]
Does that happen to all beatmaps? Can you search this songs folder for the map it fails to open? Can you find it? If so, try finding it in the /Songs endpoint.

**Comment by TheEZIC** [comment]
![image](https://user-images.githubusercontent.com/35061249/91640407-15958a00-ea26-11ea-9773-8476831f3d84.png)
![image](https://user-images.githubusercontent.com/35061249/91640416-1d552e80-ea26-11ea-959e-a068ef4a55bf.png)
![image](https://user-images.githubusercontent.com/35061249/91640431-2c3be100-ea26-11ea-9904-9b564d21502e.png)

**Comment by l3lackShark** [comment]
Link the mapset here.

**Comment by TheEZIC** [comment]
https://osu.ppy.sh/beatmapsets/1148641#mania/2398090

**Comment by TheEZIC** [comment]
It heppens on random beatmaps, each time when I reboot program they are different

**Comment by l3lackShark** [comment]
can't reproduce. Your hard drive is likely corrupt. 
![image](https://user-images.githubusercontent.com/20248967/91640496-6e215300-ea37-11ea-8152-a5a825679896.png)
Please try testing against osuSync or StreamCompanion.

**Comment by TheEZIC** [comment]
![image](https://user-images.githubusercontent.com/35061249/91640531-ea5f6a80-ea26-11ea-9c08-f42d1a137d04.png)
work

**Comment by l3lackShark** [comment]
Please try moving the whole Songs folder to another Hard Drive, then specify that path in your osu.$USER.cfg, see if that helps.

**Comment by TheEZIC** [comment]
![image](https://user-images.githubusercontent.com/35061249/91640595-5b9f1d80-ea27-11ea-9b27-ed2616bab04f.png)
![image](https://user-images.githubusercontent.com/35061249/91640598-622d9500-ea27-11ea-8465-22af083c047d.png)
![image](https://user-images.githubusercontent.com/35061249/91640602-678adf80-ea27-11ea-9c3b-d736d5be72f7.png)
Another example. I will try to move to another hdd, but it will take about an hour. Please wait

**Comment by l3lackShark** [comment]
Not needed anymore, was able to reproduce. It's a very old bug that I have no control over. Not sure on whether I can fix or not. Will try anyways.

**Comment by TheEZIC** [comment]
Ok, thanks. This is cool software, because I like websockets. Working with sync without them is a problem.

**Comment by l3lackShark** [comment]
d5fef24844cc36c702b24a23429d5bd441125f36
