### ISSUE TITLE
Very frequent mp3 errors

### ISSUE THREAD

**Issue by takoz53** [l3lackShark/gosumemory#25]
Every few maps I get the error that It could not find the specific mp3 file, resulting in values not displaying correctly.

My directory is C:\Games\osu!\Songs\{Song Folder}

I doubt that is the issue. I can replicate this issue as much as I want for instance with [this](https://osu.ppy.sh/beatmapsets/1124391#osu/2349467) beatmap.

Let me know if I need to send in any details, e.g. logs if there are any.

**Comment by l3lackShark** [comment]
Cannot reproduce, need more details. Can you go to the http://localhost:24050/json and see if the `metadata` object is populated? 
![image](https://user-images.githubusercontent.com/20248967/92288799-a76e2d00-ef27-11ea-970f-d22c8fdb405a.png)

**Comment by takoz53** [comment]
It is populated. Now I can't reproduce it either for some reason. It just happened a lot when I was streaming. Unsure how to reproduce. Any idea why it might happen?

**Comment by takoz53** [comment]
Alright, got an example ss. This happened a lot throughout the stream.
https://puu.sh/GpQMk/29a865a421.png
https://puu.sh/GpQM6/ff6cf36c5e.png

**Comment by l3lackShark** [comment]
Yeah, this is definitely  #23

**Comment by takoz53** [comment]
basically non fixable?

**Comment by l3lackShark** [comment]
It's a floating bug in the package that was written by a guy that primarily uses Linux. This will be fixed sooner or later but I cannot give any dates.

**Comment by l3lackShark** [comment]
Should hopefully be resolved in d5fef24844cc36c702b24a23429d5bd441125f36
