### ISSUE TITLE
[Enhancement] PPIfRestSS

### ISSUE THREAD

**Issue by takoz53** [l3lackShark/gosumemory#26]
I didn't find it in the JSON so I thought I'd request it.

Currently PP is only showed for FCs, e.g. I miss, it still shows max PP for current accuracy.
Say I have 90% Accuracy on Cry Thunder, it'd say ~500pp even though I just got a 100 on the first few notes. In reality the play can still be a 700pp play. I could also get  e.g. 5 misses and then FC rest and It'd show 650pp for a 99% 5 miss run.

Therefore I wanted to ask whether you could implement a PP calculation if the rest was SS'd on the map.
For example (Arbitrary values):
Max PP: 700
1x100: 695
1xmiss: 559

Hopefully I could explain it somehow.

**Comment by l3lackShark** [comment]
Could implement, but moderate effort is required. Oppai API exposes total amount of hitobjects and a [n] object at a given time in milliseconds. A function that will calculate accuracy based on that is needed.

**Comment by l3lackShark** [comment]
c3ce06c0b76a807c6a8a2b082f8d350fbba2ec84, Should not require any changes on the frontend. If fc now defaults to ifSSRest. Thanks for pointing out.
