### ISSUE TITLE
It seems like we lost the process, retrying!

### ISSUE THREAD

**Issue by HypeLevels** [l3lackShark/gosumemory#30]
This is more of asking support unfortunatelly i didnt find any place to ask other than here (perhaps im blind? ahah) anyways, yesterday the first time i executed gosumemory it worked perfectly fine, i probably did something and now i seem to be spammed with this message
![image](https://user-images.githubusercontent.com/61633775/93941171-bfb2ba00-fd25-11ea-828d-5f0c5b442ee3.png)
I already reinstalled to assure it was not something i have done but that didnt fix the issue, im still able to access the built-in overlays but not the /json endpoint :( any idea of a fix for this? or is it a known bug?

**Comment by l3lackShark** [comment]
Is your game running?

**Comment by HypeLevels** [comment]
Uh apparently it was something related with my end, restarting the computer seems to have fixed it? Osu wasnt being detected or something...
