### ISSUE TITLE
http://localhost:24050 not working!

### ISSUE THREAD

**Issue by heartfuI** [l3lackShark/gosumemory#31]
im not sure what is happening, i went to song select, i got the mania message, i exit the program, http://localhost:24050 isnt working. i installed both 64 and 32, i unzipped them both, help!

**Comment by l3lackShark** [comment]
> i exit the program
Am i reading this right? You need to have it running.

**Comment by osugenics** [comment]
> > i exit the program
> 
> Am i reading this right? You need to have it running.

yeah I agree. You need to keep gosumemory open to make http://localhost:24050 work. Hope this helps!
