### ISSUE TITLE
Sliderbreaks are broken

### ISSUE THREAD

**Issue by l3lackShark** [l3lackShark/gosumemory#32]
Due to recent changes in osu, watching replays doesn't count as 'plays' in memory anymore.

**Comment by MyAngelRem** [comment]
#59

**Comment by C0D3-M4513R** [comment]
This also happens, when playing a map, and then hitting replay.

![screenshot010](https://user-images.githubusercontent.com/28912031/112056800-bd0c1280-8b58-11eb-9419-c28c4396798e.jpg)
![screenshot011](https://user-images.githubusercontent.com/28912031/112056804-be3d3f80-8b58-11eb-8d0d-456662d9d341.jpg)

**Comment by l3lackShark** [comment]
#61
