### ISSUE TITLE
Inconsistency with JSON pp values

### ISSUE THREAD

**Issue by Enhu** [l3lackShark/gosumemory#34]
I was playing around with the pp values inside the menu object and every time I enter a map to play it randomly changes its values, sometimes it changes them, sometimes it doesn't. It also sometimes fixes itself by going back to the map selection menu but other times it displays the wrong values.

```
...
"pp": {
  95: 180
  96: 186
  97: 195
  98: 207
  99: 224
  100: 249
...
```

```
...
"pp": {
  95: 13
  96: 19
  97: 28
  98: 41
  99: 59
  100: 85
...
```

I'm guessing this is the max pp the map can give with or without mods right? I was trying to use it that way but I kept getting these inconsistencies when playing a map.

![chrome_2020-10-04_22-17-38](https://user-images.githubusercontent.com/13659048/95032519-46a25380-0691-11eb-980b-b9ebad6bb33f.png)

**Comment by l3lackShark** [comment]
Already fixed via cb43f479825f4bef516f1015acd9efbc0d80308e, download latest artifact if you want it right now.
