### ISSUE TITLE
gameplay.pp.maxThisPlay sometimes broken

### ISSUE THREAD

**Issue by viddie** [l3lackShark/gosumemory#38]
My impression of this attribute was that if, from any given point in a play, you SS everything, that will be the pp you get at the end. However, sometimes after breaking combo this value slowly decreases even while playing perfectly. That isn't really the maximum then, or am I misinterpreting this attribute?

Video of this happening (see the pp-bar at the right side at around 0:22): https://www.youtube.com/watch?v=v9cMb2aP_Rw

**Comment by l3lackShark** [comment]
![image](https://user-images.githubusercontent.com/20248967/98162841-beb79f80-1f03-11eb-83a5-4617ebaa96f3.png)
As explained in the wiki, this value indicates maximum amount of pp possible from a given play (including past hit judgments)

**Comment by viddie** [comment]
Yes i get that part. Let's say I get a couple of 100's and misses early on and from there SS the rest of the map. At any given point during the SS part until the end, shouldn't the maxThisPlay be the same value, as you are literally on your way to get the maximum amount of pp you can with the misses/acc loss?

**Comment by l3lackShark** [comment]
This is probably not the behavior that we are expecting, could be a regression, will look at it

**Comment by l3lackShark** [comment]
Can I have this replay? @viddie

**Comment by viddie** [comment]
Sure, here you go https://fu.vi-home.de/f/sLofHRl7 (direct download)

**Comment by l3lackShark** [comment]
[Attempt ](246221f05518ea089858f9f3280a12d5993281da) was made to fix that, test build could be obtained here: https://github.com/l3lackShark/gosumemory/runs/1355174754

**Comment by l3lackShark** [comment]
Had to redo that job, [Here ](https://github.com/l3lackShark/gosumemory/runs/1355188950) is the build.

**Comment by viddie** [comment]
That seems to have fixed the issue. I'll repoen this if it does happen to occur again. Thanks!
