### ISSUE TITLE
fopen: No such file or directory

### ISSUE THREAD

**Issue by th1nkh4rd** [l3lackShark/gosumemory#40]

**Comment by HerendraTJ** [comment]
Someone close this issue since minimum effort of issue. Close it

**Comment by l3lackShark** [comment]
This is usually related to non-English characters in input path to oppai. Please see [this](https://github.com/Francesco149/oppai-ng/issues/62) for details. It is our current limitation and not much I can do about it at the moment.

**Comment by l3lackShark** [comment]
Reopening for visibility

**Comment by th1nkh4rd** [comment]
thx

**Comment by l3lackShark** [comment]
Hopefully fixed in 0630d5d5da58930daa60cd65ade05ea13d8afb39
