### ISSUE TITLE
Failure mid getting offsets, retrying! ERROR: no memory matched the pattern

### ISSUE THREAD

**Issue by YourSandwich** [l3lackShark/gosumemory#43]
Hello, like 1Month ago i used gosumemory normaly on Linux it worked with sudo and trough wine.
Now i got back to gosumemory and updated it but i get this messege and cant bring it to run.

Specs:
OS: Manjaro Linux x64 
Kernel: 5.10.0-101-tkg-pds 

osu! running trough wine 6.0 x64
Latest osu cuttinedge b20201210

The Error message:
![image](https://user-images.githubusercontent.com/20018243/102260234-7b901980-3f10-11eb-81d7-c57e3f53b2f6.png)

**Comment by l3lackShark** [comment]
Bad WINEPREFIX is usually the cause. https://gitlab.com/osu-wine/osu-wine should work fine with us. Get [this](https://gitlab.com/osu-wine/osu-wineprefix) if you know how to deal with wineprefixes.

**Comment by l3lackShark** [comment]
Also htop is worth checking. Make sure that there is no running `osu!.exe` processes when your game is closed. osu's process sometimes gets stuck. (htop > F4 > "osu"  > (if present) > F9 > 9 > Enter)

**Comment by YourSandwich** [comment]
> Bad WINEPREFIX is usually the cause. https://gitlab.com/osu-wine/osu-wine should work fine with us. Get [this](https://gitlab.com/osu-wine/osu-wineprefix) if you know how to deal with wineprefixes.
Yup your wine prefix is working, thanks :)

**Comment by l3lackShark** [comment]
Glad to help!
