### ISSUE TITLE
Current plays displaying as NM instead with mods after the song ends.

### ISSUE THREAD

**Issue by RoARene317** [l3lackShark/gosumemory#44]
Problem that I encountered : 
Every gameplay on current PP use the NM Current instead with mods as you can see in this JSON. On previous version this data is fine until this happened. 
![image](https://user-images.githubusercontent.com/24410807/103220022-cae33a80-4951-11eb-867c-8ef6881b71e2.png)

For the replay data, here I will attach you my osr for investigation. 
OSR Plays : https://drive.google.com/file/d/1zBQGgSfgg1h4g5dc3WBR_2B_ro3SxtIt/view?usp=sharing
Also here is the beatmap links for related osr : https://osu.ppy.sh/beatmapsets/914242#osu/1919496

Version : 1.3.1

**Comment by l3lackShark** [comment]
2aa31b0
