### ISSUE TITLE
100%pp(Max PP) not working properly in mania mode.

### ISSUE THREAD

**Issue by t2rm1nator** [l3lackShark/gosumemory#45]
I wrote the following code.

![image](https://user-images.githubusercontent.com/76769710/103338339-6e069200-4ac1-11eb-86bf-f1ca36ab76b3.png)

but result not working. only see 0pp.
this only works in standard mode.
I have used the items in gameplay.pp , but only the current item works properly.
![image](https://user-images.githubusercontent.com/76769710/103338218-0a7c6480-4ac1-11eb-9898-004e08bf2f9b.png)

**Comment by Dartandr** [comment]
These stats are not implemented for mania yet. Use `gameplay.pp.fc` for now as it will always have a million score value in it. This will probably change somewhere down the line when proper mania stats will be implemented.

**Comment by t2rm1nator** [comment]
Well, gameplay.pp.fc still not working.... only 0 is displayed. Most of items are produced based on the standard mode. So, time.mp3, firstObj, bm.stats.CS(key), etc not working mania mode.  I hope it will be supported in the next version. Thank you for your answer.

**Comment by Dartandr** [comment]
Please make sure that mania gamemode is selected in SongSelect 
![image](https://user-images.githubusercontent.com/32641958/103445626-bc658d80-4c87-11eb-9e62-715f624dd4d5.png)

**Comment by t2rm1nator** [comment]
OK. I changed mania gamemode in songselect screen. I thought it was solved, but it wasn't. PP value appears and disappears quickly.
![GIF 2021-01-05 오전 1-34-04](https://user-images.githubusercontent.com/76769710/103557408-7f530280-4ef6-11eb-9735-dc60fff01eb7.gif)
the value stored in the maxPP variable is zero.

**Comment by l3lackShark** [comment]
maxThisPlay is STD only. Is the `gameplay.pp.fc` also flickering?

**Comment by t2rm1nator** [comment]
yes. I use gameplay.pp.fc . I don't know what the problem is.
![image](https://user-images.githubusercontent.com/76769710/103613958-e0b4b900-4f6a-11eb-94a7-7c54f65d5489.png)

**Comment by l3lackShark** [comment]
Will look at it

**Comment by l3lackShark** [comment]
2aa31b0d310bda1ffc7f07728c2abfd7b90db5a2 should hopefully resolve this. Please get [this](https://github.com/l3lackShark/gosumemory/actions/runs/465211126) artifact and confirm.

**Comment by l3lackShark** [comment]
Actually after some further investigation it seems that the issue was with the variable setting itself. `menu.pp[100]`  should give million score pp in mania now. Please test [this](https://github.com/l3lackShark/gosumemory/actions/runs/465304131) and confirm.

**Comment by l3lackShark** [comment]
`gameplay.pp.fc` still gives the million value but that will be deprecated when actual fc calculator will be implemented. Use the token above from now on.
