### ISSUE TITLE
Is there a way to access the webpage from another computer within the same network?

### ISSUE THREAD

**Issue by saieeshb** [l3lackShark/gosumemory#46]
I tried doing http://192.168.0.108:24050 from my other device and it doesn't connect. I tried doing this but it looks like gosumemory listens only on the localhost.I s there a way I could configure it to see the webpage from another computer within the same network?

Cheers!

**Comment by l3lackShark** [comment]
Follow [these](https://www.youtube.com/watch?v=scV0-H5MtDE) steps
