### ISSUE TITLE
hp and nm.time working incorrect

### ISSUE THREAD

**Issue by cyperdark** [l3lackShark/gosumemory#47]
in past https://www.youtube.com/watch?v=77HKT5EznvY
now https://www.youtube.com/watch?v=Dhr9_ZI3338

**Comment by l3lackShark** [comment]
Please test on 1.3.0, 1.3.1 and latest artifact. All on same beatmap and come back with a comparison video. I had an idea on what that could be and if it is what i think it is it should be fixed in the latest artifact. Your design is proprietary so i can't really test anything myself.

**Comment by cyperdark** [comment]
1.3.0 https://youtu.be/rPk_4_vjHZU
1.3.1 https://youtu.be/BGnBKfygsvc
