### ISSUE TITLE
Currents mods and difficulty statistics resetted to NM after song ends.

### ISSUE THREAD

**Issue by RoARene317** [l3lackShark/gosumemory#48]
Referring to issue number #44 , similar but right now the Difficulty of the beatmaps and also the Mods that used in game resetted when in result screen.

OSR Plays : https://drive.google.com/file/d/1zBQGgSfgg1h4g5dc3WBR_2B_ro3SxtIt/view?usp=sharing
Also here is the beatmap links for related osr : https://osu.ppy.sh/beatmapsets/914242#osu/1919496

I already attached you also the .sql that maybe help you to solve this issue.
[reportbug.zip](https://github.com/l3lackShark/gosumemory/files/5837864/reportbug.zip)

Version : Artifacts 1.3.1 (https://github.com/l3lackShark/gosumemory/actions/runs/465304131)

**Comment by l3lackShark** [comment]
5a67d42593a0be4e087831239cadddbfe5f40f8f
