### ISSUE TITLE
osu folder & fix backslashes

### ISSUE THREAD

**Issue by cyperdark** [l3lackShark/gosumemory#49]
- [ ] add path to osu in `settings.folders.osu`
- [ ] `settings.folders.songs` & `settings.folders.osu` change backshashes to slash

**Comment by l3lackShark** [comment]
first is fine but if you want the second then use Linux or blame Microsoft for giving a middle finger to filepath separator standards that the rest of the world uses. Paths are OS specific. It might work better for you in JavaScript to have them use forward slashes, but some use cases might require them to stay OS specific. Not doing that one for compatibility reasons.

**Comment by l3lackShark** [comment]
2f5ebfce1949629ec74a44e517a705c1f21f430e
