### ISSUE TITLE
Gosumemory ignore second team in tournamet mode

### ISSUE THREAD

**Issue by Lewui** [l3lackShark/gosumemory#50]
When i use gosumemory for tournament client, only first team players shows second just ignored(?)

**Comment by l3lackShark** [comment]
Sorry for not stating it anywhere as tournament mode is still kind of in beta but we only support Cutting Edge tourney client.

**Comment by Lewui** [comment]
Uhh, maybe you can help with this problem? If i understand you right, i use Cutting Edge tourney client

https://streamable.com/tnaw7m

**Comment by l3lackShark** [comment]
No you're not. I can tell that it's `stable` branch just by looking at yellow names in the slots. Make sure that you are on `Cutting Edge`.

**Comment by Lewui** [comment]
Ok, i re-checked you are right, i'm in Cutting Edge now. 
![image](https://user-images.githubusercontent.com/49539029/106148917-4f5bef80-6182-11eb-8267-b60d7c59095b.png)

And... It works now! Sorry for so stupid mistake, i thought i'm on Cutting Edge... But I doubted because the text is yellow.
