### ISSUE TITLE
Is it allowed to use the addresses and offsets in read.go in a repository under the MIT License?

### ISSUE THREAD

**Issue by UnnamedOrange** [l3lackShark/gosumemory#53]
As the title says, I would like to use ONLY the addresses and offsets in [read.go](https://github.com/l3lackShark/gosumemory/blob/master/memory/read.go). Is it possible to use them and remain my repository under the MIT License at the same time? Namely, could I be granted the rights to use them with a thank instead of making a reference of this repository :)

My code that refers to them is [here](https://github.com/UnnamedOrange/osu-memory/blob/main/osu-memory/include/osu_memory_module_hit.hpp).

Best regrads.

**Comment by l3lackShark** [comment]
Yes I have nothing against that, besides the fact that I do not own rights to all of these signatures myself. (see [this](https://github.com/l3lackShark/gosumemory#special-thanks-to)). So all I want is a reference to this and [ProcessMemoryDataFinder](https://github.com/Piotrekol/ProcessMemoryDataFinder) repositories.

**Comment by UnnamedOrange** [comment]
Thank you for your generosity.
