### ISSUE TITLE
Doesnt work gameoverlay when gameoverlay set - true

### ISSUE THREAD

**Issue by 404n1xware** [l3lackShark/gosumemory#57]
I open **gosumemory.exe** open osu! and **gameoverlay** dont work, and and after 5 - 10 minutes it crashes

https://prnt.sc/10kalj9 - config.ini

https://prnt.sc/10kam3e - The problem.

Help me please! Contact - n1xware#1337

**Comment by l3lackShark** [comment]
We don't support compatibility mode, make sure it's disabled

**Comment by l3lackShark** [comment]
https://discord.gg/QPTUGnRN

**Comment by 404n1xware** [comment]
Wdym?

**Comment by l3lackShark** [comment]
Get to the russian support channel in our discord server, I'm not sure if github issues is suitable in this situation.
