### ISSUE TITLE
Failed to inject into osu's process (In-Game Overlay)

### ISSUE THREAD

**Issue by byzocker** [l3lackShark/gosumemory#58]
I honestly don't know how this happend, but before it worked and now it doesn't work anymore
![image](https://user-images.githubusercontent.com/59401089/111035674-c809c900-841b-11eb-86f2-367432cfcbb8.png)

**Comment by RoARene317** [comment]
Try run gosumemory as admin.

**Comment by byzocker** [comment]
Well that fixed it
