### ISSUE TITLE
OBS not detecting Web-based counter, errors in bash etc...

### ISSUE THREAD

**Issue by Maritsu** [l3lackShark/gosumemory#65]
## Unable to connect to `localhost:24050` (connection refused)
![gosumemory is running, `localhost:24050` isn't working](https://user-images.githubusercontent.com/66056347/113421190-ef283a80-93ca-11eb-9665-8e22cc732cdb.png)

## OBS not detecting web counter
![`localhost:24050/Simplistic` doesn't show anything when opened in OBS](https://user-images.githubusercontent.com/66056347/113421288-1f6fd900-93cb-11eb-9abe-6c38cc83a663.png)

## Errors in bash
![keeps spitting out this error: ```2021/04/02 15:52:11 Failure mid getting offsets, retrying! ERROR: no memory matched the pattern: 83 E0 20 85 C0 7E 2F```](https://user-images.githubusercontent.com/66056347/113421430-64940b00-93cb-11eb-97db-d7c71f487905.png)

## System info
Ubuntu 20.04.2 LTS, 64-bit, Linux `5.8.0-48-generic` (default) kernel

<details open>
<summary>config.ini</summary>

```ini  
[Main]
update = 100
path = /home/bittheprotogen/Games/osu/Songs
cgodisable = false
memdebug = false
memcycletest = false
wine = true
		
[Web]
serverip = 127.0.0.1:24050
cors = false
		
[GameOverlay] ; https://github.com/l3lackShark/gosumemory/wiki/GameOverlay
enabled = true
gameWidth = 1920
gameHeight = 1080
overlayURL = http://localhost:24050/Simplistic
overlayWidth = 355
overlayHeight = 97
overlayOffsetX = 0
overlayOffsetY = 0
overlayScale = 10

**Comment by l3lackShark** [comment]
Please launch native Linux version with sudo privileges, as stated in the README.

**Comment by l3lackShark** [comment]
Also, only dotnet 4.5 runtime is supported. Make sure that it's the one that running your osu instance.

**Comment by Maritsu** [comment]
Thanks for the help!
