### ISSUE TITLE
Scrollbar shown when using negative absolute positions

### ISSUE THREAD

**Issue by ItsShamed** [l3lackShark/gosumemory#69]
For the past few days, I was experimenting a little bit with gosumemory (tried to make my own overlay), and I noticed that whenever my overlay was transitioning (start of a game/replay or end of game/replay), it would show a scrollbar at the bottom.

To be honest, it's not a big deal, it's not breaking things, it's just visual *(and maybe I've done something wrong on my overlay lol)*.
But I'm submitting this issue anyways in case it would be useful idk.

Video example: https://www.youtube.com/watch?v=tRowPLGuFco
*Pay attention to the bottom of the screen when I'm starting the replay and when the replay is finished. (I was lazy to cut the gameplay)*

**Comment by l3lackShark** [comment]
set `overflow:hidden` to the body. https://github.com/l3lackShark/static/blob/85ee9299ce095c8c07512c188c5e64167a55b33e/VictimCrasherCompact/css/style.css#L8

**Comment by ItsShamed** [comment]
Oh god how could I forgot something simple as that lol, thanks for reminding me this.
