### ISSUE TITLE
failed to inject into osu's process, in game overlay will be unavailable.

### ISSUE THREAD

**Issue by gunderdogs** [l3lackShark/gosumemory#70]
![tech](https://user-images.githubusercontent.com/83116551/115954434-636e7d80-a534-11eb-8dd1-b927679ae005.PNG)
error in attached picture

tried:
- setting cors to true
- cgodisable to true
- in another resolution (1366x768)
- both ingame1 and 2 with the respective overlay width/heights
- overlayscale to 1 instead

![tech 2](https://user-images.githubusercontent.com/83116551/115954488-b6483500-a534-11eb-9f15-a7200298ac99.PNG)

**Comment by gunderdogs** [comment]
also tried running as admin

**Comment by l3lackShark** [comment]
Maybe something happened during initial download of the zip file, try deleting `gameoverlay.zip`

**Comment by gunderdogs** [comment]
unable to find gameoverlay.zip, don't think it downloaded?

**Comment by HerendraKurniawan** [comment]
> unable to find gameoverlay.zip, don't think it downloaded?

Your AV delete gosumemory since it's inject to osu! process. Please exclude gosumemory to your AV and try redownload again

**Comment by gunderdogs** [comment]
what is AV? and how do I exclude it?

**Comment by l3lackShark** [comment]
> what is AV? and how do I exclude it?

Antivirus. Due to the way the overlay works, it might get triggered by some antiviruses. Try temporarily disabling it and/or download this manually: https://omk.pics/12/wVugx and put the contents of that into `gameoverlay` folder.

**Comment by gunderdogs** [comment]
thankyou to both, disabling av allowed for gameoverlay download :D everything else worked after that
