### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by ViolentVHWeaponzz** [l3lackShark/gosumemory#73]
How to set this up?

**Comment by Dartandr** [comment]
https://github.com/l3lackShark/gosumemory#usage

**Comment by ViolentVHWeaponzz** [comment]
> https://github.com/l3lackShark/gosumemory#usage

Is OBS free? I don't want to spend 20 dollahz on that fucking thing.

**Comment by Sibyl666** [comment]
@ViolentVHWeaponzz it's totally free
