### ISSUE TITLE
scrollbar on in-game overlay

### ISSUE THREAD

**Issue by 4zjata** [l3lackShark/gosumemory#74]
when i load maximalLime as in-game overlay i can see scrollbar 
![image](https://user-images.githubusercontent.com/63453921/118536069-8e22af00-b74b-11eb-9ed6-52adbf980c10.png)

**Comment by l3lackShark** [comment]
[Redownload](https://github.com/l3lackShark/static/archive/refs/heads/master.zip) static folder

**Comment by l3lackShark** [comment]
You also might need to clear gameoverlay cache. (delete `gameoverlay/cache` folder)

**Comment by 4zjata** [comment]
thanks
