### ISSUE TITLE
It seems that we lost the process, retrying! ERROR: no process matching the criteria was found

### ISSUE THREAD

**Issue by WoodyTheMighty** [l3lackShark/gosumemory#77]
This error message is popping up for me 
"It seems that we lost the process, retrying! ERROR: no process matching the criteria was found"

**Comment by l3lackShark** [comment]
Make sure that your game is not running with admin rights (you can check if it does by running gosumemory as admin)

**Comment by l3lackShark** [comment]
(by checking i mean that it will start working) but instead of running gosumemory with admin rights every time, don't run your game with admin.

**Comment by Katerang31** [comment]
i'm having the same issue, i tried running it as an admin.

**Comment by ShibEly** [comment]
I am too having this issue and have no clue what to do :3

**Comment by Katerang31** [comment]
MAKE SURE UR GAME IS OPEN
