### ISSUE TITLE
Gosu uses the old taiko SR calculation

### ISSUE THREAD

**Issue by lolxdhi1** [l3lackShark/gosumemory#80]
A NM SS on [this map](https://osu.ppy.sh/beatmapsets/928431#taiko/1939224) is currently worth 178pp, but Gosu displays it in-game as 399pp
![LtTA3i2](https://user-images.githubusercontent.com/47082567/123297383-6e7f6300-d50f-11eb-9c23-6135f6a8f652.png)

**Comment by Dartandr** [comment]
We use third party [pp calculator](https://github.com/Francesco149/oppai-ng) Go ahead and ask them to update the taiko formula.

**Comment by Dartandr** [comment]
https://github.com/Francesco149/oppai-ng/issues/64
