### ISSUE TITLE
gosumemory can't catch v2 score data

### ISSUE THREAD

**Issue by SugiuraAyano** [l3lackShark/gosumemory#84]
I've trying to do showcase in tournament with gosumemory. when playing the replay files it can't read score properly and it stuck at 0 point.
![image](https://user-images.githubusercontent.com/44806508/125202061-8e02e380-e2a4-11eb-8c5f-82d1c61c8d97.png)
accuracy and combo is displayed normally

**Comment by SugiuraAyano** [comment]
oh i saw the commit and you're already implement that

**Comment by l3lackShark** [comment]
Yeah, latest commit artifact should work, although its unstable

**Comment by SugiuraAyano** [comment]
ok i will try to build it. will close this now

**Comment by SugiuraAyano** [comment]
ok i will try to build it. will close this now

**Comment by l3lackShark** [comment]
No need to build, just get [this](https://github.com/l3lackShark/gosumemory/suites/3122062979/artifacts/71535526) artifact

**Comment by SugiuraAyano** [comment]
thanks a lot!
