### ISSUE TITLE
Failed to inject into osu's process, in game overlay will be unavailabe

### ISSUE THREAD

**Issue by nirlikbtw** [l3lackShark/gosumemory#89]
![2021-08-02](https://user-images.githubusercontent.com/88336728/127888249-16695d2e-2bb7-433a-8274-c8f3296a9e73.png)
I don't get it please help

**Comment by l3lackShark** [comment]
Your antivirus probably deletes the files necessary to run the overlay

**Comment by nirlikbtw** [comment]
how do i disable it?
