### ISSUE TITLE
I wanna know the number which these rankedstatus stand

### ISSUE THREAD

**Issue by Adsicmes** [l3lackShark/gosumemory#91]
![image](https://user-images.githubusercontent.com/79645438/129338319-31cae262-e4dd-4058-93fb-a4e78a13fc05.png)

**Comment by l3lackShark** [comment]
These are ascending order, left to right.

**Comment by Adsicmes** [comment]
![image](https://user-images.githubusercontent.com/79645438/129339281-4ebb0ed7-4df9-4a5b-9130-1672808e8a38.png)
this is ranked   but it was the fifth

**Comment by l3lackShark** [comment]
![image](https://user-images.githubusercontent.com/20248967/129339479-57f3c54f-eaf0-45ac-9444-1fc72461f91e.png)

**Comment by Adsicmes** [comment]
![4OJ`J5%F_)I{6}8 0C%98YC](https://user-images.githubusercontent.com/79645438/129340091-4b67bb19-d350-4f66-9bc5-04d75ae76220.jpg)
ah  thanks
