### ISSUE TITLE
Changing Overlay code requires deletion of gameoverlay/cache

### ISSUE THREAD

**Issue by C0D3-M4513R** [l3lackShark/gosumemory#96]
It is normal, that changing the overlay code requires deletion of gosumemory/gameoverlay/cache?

I am running into repeated problems where i change some js code, but the new js code isn't executed.
That is, until the before mentioned dir. is deleted. Then the new code gets run.

fixes C0D3-M4513R/twitch-static#6

**Comment by l3lackShark** [comment]
It's an intended behavior that will be changed in the future. But why can't you just test in your browser? GameOverlay behaves exactly like Chrome.

**Comment by C0D3-M4513R** [comment]
That is a user abjustable file.
It containes generic information about the bot, like if it is enabled.

If the user wants to disable the bot, he will have to close gosumemory (it is locking cache), osu! (it is also locking cache) then delete cache and change a setting.

This gets annoying really quickly. I will admit though, that this is an edge case. I could/should probably just fork gosumemory. (except I do not want to do that since this project is not fully open source)
https://github.com/C0D3-M4513R/twitch-static/blob/master/twitch.js

**Comment by l3lackShark** [comment]
GameOverlay is proprietary and so you can't do anything about this behavior. I will remove the cache all together.

**Comment by C0D3-M4513R** [comment]
Dev exists in discord now.
