### ISSUE TITLE
 Failure mid getting offsets, retrying! ERROR: no memory matched the pattern: 0A D7 23 3C 00 00 ?? 01

### ISSUE THREAD

**Issue by Turnhell** [l3lackShark/gosumemory#99]
when i open the gosumemory when the app get the osu! stat adress lunchs me a error like this:   Failure mid getting offsets, retrying! ERROR: no memory matched the pattern: 0A D7 23 3C 00 00 ?? 01 how i can fix this?
![imagen_2021-10-09_002013](https://user-images.githubusercontent.com/92195640/136642394-45a05cdc-0630-490b-8bd1-db447820a936.png)

**Comment by l3lackShark** [comment]
Are you running your game as admin? Latest osu! version?

**Comment by l3lackShark** [comment]
> 
> 
> > Are you running your game as admin? Latest osu! version?
> 
> Yes, always runing as admin, and i use the latest version of osu!.

Never launch osu! as admin and gosumemory will work.
